name: notepad
description: Note App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  asuka: ^2.0.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.9
  icons_launcher: ^1.1.7
  libv_markdown: ^1.0.2
  rx_notifier: ^1.1.0
  share_plus:
  sqflite: ^2.0.2
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/icon/ic_logo.png'
  ios: true
  android: true

flutter:
  uses-material-design: true

  assets:
    - assets/
